#!/usr/bin/python3
# What is the expected output of the following code snippet ?

my_list = [ x for x in range(20) if x % 2 == 0 if x % 5 == 0]
print(my_list)

# Explanation
# Knowledge Area : Miscellaneous

# Topic : list comprehension: if operator

# Explanation:

# my_list  is a list comprehension and its elements are generated by : x for x in range(20) if x % 2 == 0 if x % 5 == 0

# x for x in range(20)  is sequence 0..19.

# Out of this sequence, we need to find the numbers that are multiple of two (i.e. even) and multiple of five (i.e. their division by 5 has a remainder of zero) : only 0 and 10 meet this requirement.

# So, correct answer is : [0, 10]