#!/usr/bin/python3
# What is the expected output of the following code snippet ?

my_list1 = ['$ABC','56HN','PYKN','&HYJ','THDF','SDE#','ONDE']
my_list2 = [ x[0] + x[1] for x in my_list1 if x.isalpha()]
print(''.join(my_list2))

# Explanation:

# my_list2  is a list comprehension and its elements are generated by : x[0] + x[1] for x in my_list1 if x.isalpha().

# isalpha()  is a string method and returns True if the string contains only letters, and False otherwise.

# x[0] + x[1] is the concatenation of the first letter and second letter from string x.

# So, my_list2 includes the elements from my_list1 that contains letters only and, for those, the first two letters are concatenated - in other words :

# ['PY','TH','ON']

# Finally, with the join() method applied to my_list2  with separator '', the end result is :

# PYTHON